// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: test_hooks_cross_module2_heap_storage.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct CrossModule2_HeapStorage_Msg {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var field1: Int32 {
    get {return _storage._field1 ?? 0}
    set {_uniqueStorage()._field1 = newValue}
  }
  /// Returns true if `field1` has been explicitly set.
  public var hasField1: Bool {return _storage._field1 != nil}
  /// Clears the value of `field1`. Subsequent reads from it will return its default value.
  public mutating func clearField1() {_storage._field1 = nil}

  public var field2: Int32 {
    get {return _storage._field2 ?? 0}
    set {_uniqueStorage()._field2 = newValue}
  }
  /// Returns true if `field2` has been explicitly set.
  public var hasField2: Bool {return _storage._field2 != nil}
  /// Clears the value of `field2`. Subsequent reads from it will return its default value.
  public mutating func clearField2() {_storage._field2 = nil}

  public var forceHeapStorage: CrossModule2_HeapStorage_Msg.Sub {
    get {return _storage._forceHeapStorage ?? CrossModule2_HeapStorage_Msg.Sub()}
    set {_uniqueStorage()._forceHeapStorage = newValue}
  }
  /// Returns true if `forceHeapStorage` has been explicitly set.
  public var hasForceHeapStorage: Bool {return _storage._forceHeapStorage != nil}
  /// Clears the value of `forceHeapStorage`. Subsequent reads from it will return its default value.
  public mutating func clearForceHeapStorage() {_storage._forceHeapStorage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Forcing this message to use heap storage.
  public struct Sub {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var a: Int32 {
      get {return _a ?? 0}
      set {_a = newValue}
    }
    /// Returns true if `a` has been explicitly set.
    public var hasA: Bool {return self._a != nil}
    /// Clears the value of `a`. Subsequent reads from it will return its default value.
    public mutating func clearA() {self._a = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _a: Int32? = nil
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct CrossModule2_HeapStorage_MsgAsField {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var asField: CrossModule2_HeapStorage_Msg {
    get {return _storage._asField ?? CrossModule2_HeapStorage_Msg()}
    set {_uniqueStorage()._asField = newValue}
  }
  /// Returns true if `asField` has been explicitly set.
  public var hasAsField: Bool {return _storage._asField != nil}
  /// Clears the value of `asField`. Subsequent reads from it will return its default value.
  public mutating func clearAsField() {_storage._asField = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct CrossModule2_HeapStorage_MsgInArray {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inArray: [CrossModule2_HeapStorage_Msg] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct CrossModule2_HeapStorage_MsgInArrayInHeapStorage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inArray: [CrossModule2_HeapStorage_Msg] {
    get {return _storage._inArray}
    set {_uniqueStorage()._inArray = newValue}
  }

  public var forceHeapStorage: CrossModule2_HeapStorage_MsgInArrayInHeapStorage.Sub {
    get {return _storage._forceHeapStorage ?? CrossModule2_HeapStorage_MsgInArrayInHeapStorage.Sub()}
    set {_uniqueStorage()._forceHeapStorage = newValue}
  }
  /// Returns true if `forceHeapStorage` has been explicitly set.
  public var hasForceHeapStorage: Bool {return _storage._forceHeapStorage != nil}
  /// Clears the value of `forceHeapStorage`. Subsequent reads from it will return its default value.
  public mutating func clearForceHeapStorage() {_storage._forceHeapStorage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Forcing this message to use heap storage.
  public struct Sub {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var a: Int32 {
      get {return _a ?? 0}
      set {_a = newValue}
    }
    /// Returns true if `a` has been explicitly set.
    public var hasA: Bool {return self._a != nil}
    /// Clears the value of `a`. Subsequent reads from it will return its default value.
    public mutating func clearA() {self._a = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _a: Int32? = nil
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct CrossModule2_HeapStorage_MsgInMap {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inMap: Dictionary<Int32,CrossModule2_HeapStorage_Msg> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct CrossModule2_HeapStorage_MsgInMapInHeapStorage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inMap: Dictionary<Int32,CrossModule2_HeapStorage_Msg> {
    get {return _storage._inMap}
    set {_uniqueStorage()._inMap = newValue}
  }

  public var forceHeapStorage: CrossModule2_HeapStorage_MsgInMapInHeapStorage.Sub {
    get {return _storage._forceHeapStorage ?? CrossModule2_HeapStorage_MsgInMapInHeapStorage.Sub()}
    set {_uniqueStorage()._forceHeapStorage = newValue}
  }
  /// Returns true if `forceHeapStorage` has been explicitly set.
  public var hasForceHeapStorage: Bool {return _storage._forceHeapStorage != nil}
  /// Clears the value of `forceHeapStorage`. Subsequent reads from it will return its default value.
  public mutating func clearForceHeapStorage() {_storage._forceHeapStorage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Forcing this message to use heap storage.
  public struct Sub {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var a: Int32 {
      get {return _a ?? 0}
      set {_a = newValue}
    }
    /// Returns true if `a` has been explicitly set.
    public var hasA: Bool {return self._a != nil}
    /// Clears the value of `a`. Subsequent reads from it will return its default value.
    public mutating func clearA() {self._a = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _a: Int32? = nil
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "cross_module2.heap_storage"

extension CrossModule2_HeapStorage_Msg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Msg"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "field1"),
    2: .same(proto: "field2"),
    3: .standard(proto: "force_heap_storage"),
  ]

  fileprivate class _StorageClass {
    var _field1: Int32? = nil
    var _field2: Int32? = nil
    var _forceHeapStorage: CrossModule2_HeapStorage_Msg.Sub? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _field1 = source._field1
      _field2 = source._field2
      _forceHeapStorage = source._forceHeapStorage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularInt32Field(value: &_storage._field1)
        case 2: try decoder.decodeSingularInt32Field(value: &_storage._field2)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._forceHeapStorage)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._field1 {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
      }
      if let v = _storage._field2 {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
      }
      if let v = _storage._forceHeapStorage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public func _protobuf_generated_isEqualTo(other: CrossModule2_HeapStorage_Msg) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._field1 != other_storage._field1 {return false}
        if _storage._field2 != other_storage._field2 {return false}
        if _storage._forceHeapStorage != other_storage._forceHeapStorage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CrossModule2_HeapStorage_Msg.Sub: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = CrossModule2_HeapStorage_Msg.protoMessageName + ".Sub"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "a"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self._a)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._a {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public func _protobuf_generated_isEqualTo(other: CrossModule2_HeapStorage_Msg.Sub) -> Bool {
    if self._a != other._a {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CrossModule2_HeapStorage_MsgAsField: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MsgAsField"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "as_field"),
  ]

  fileprivate class _StorageClass {
    var _asField: CrossModule2_HeapStorage_Msg? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _asField = source._asField
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._asField)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._asField {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public func _protobuf_generated_isEqualTo(other: CrossModule2_HeapStorage_MsgAsField) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._asField != other_storage._asField {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CrossModule2_HeapStorage_MsgInArray: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MsgInArray"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "inArray"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.inArray)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.inArray.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.inArray, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public func _protobuf_generated_isEqualTo(other: CrossModule2_HeapStorage_MsgInArray) -> Bool {
    if self.inArray != other.inArray {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CrossModule2_HeapStorage_MsgInArrayInHeapStorage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MsgInArrayInHeapStorage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "inArray"),
    2: .standard(proto: "force_heap_storage"),
  ]

  fileprivate class _StorageClass {
    var _inArray: [CrossModule2_HeapStorage_Msg] = []
    var _forceHeapStorage: CrossModule2_HeapStorage_MsgInArrayInHeapStorage.Sub? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _inArray = source._inArray
      _forceHeapStorage = source._forceHeapStorage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeRepeatedMessageField(value: &_storage._inArray)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._forceHeapStorage)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._inArray.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._inArray, fieldNumber: 1)
      }
      if let v = _storage._forceHeapStorage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public func _protobuf_generated_isEqualTo(other: CrossModule2_HeapStorage_MsgInArrayInHeapStorage) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._inArray != other_storage._inArray {return false}
        if _storage._forceHeapStorage != other_storage._forceHeapStorage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CrossModule2_HeapStorage_MsgInArrayInHeapStorage.Sub: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = CrossModule2_HeapStorage_MsgInArrayInHeapStorage.protoMessageName + ".Sub"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "a"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self._a)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._a {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public func _protobuf_generated_isEqualTo(other: CrossModule2_HeapStorage_MsgInArrayInHeapStorage.Sub) -> Bool {
    if self._a != other._a {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CrossModule2_HeapStorage_MsgInMap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MsgInMap"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "in_map"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt32,CrossModule2_HeapStorage_Msg>.self, value: &self.inMap)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.inMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt32,CrossModule2_HeapStorage_Msg>.self, value: self.inMap, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public func _protobuf_generated_isEqualTo(other: CrossModule2_HeapStorage_MsgInMap) -> Bool {
    if self.inMap != other.inMap {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CrossModule2_HeapStorage_MsgInMapInHeapStorage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MsgInMapInHeapStorage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "in_map"),
    2: .standard(proto: "force_heap_storage"),
  ]

  fileprivate class _StorageClass {
    var _inMap: Dictionary<Int32,CrossModule2_HeapStorage_Msg> = [:]
    var _forceHeapStorage: CrossModule2_HeapStorage_MsgInMapInHeapStorage.Sub? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _inMap = source._inMap
      _forceHeapStorage = source._forceHeapStorage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt32,CrossModule2_HeapStorage_Msg>.self, value: &_storage._inMap)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._forceHeapStorage)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._inMap.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt32,CrossModule2_HeapStorage_Msg>.self, value: _storage._inMap, fieldNumber: 1)
      }
      if let v = _storage._forceHeapStorage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public func _protobuf_generated_isEqualTo(other: CrossModule2_HeapStorage_MsgInMapInHeapStorage) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._inMap != other_storage._inMap {return false}
        if _storage._forceHeapStorage != other_storage._forceHeapStorage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CrossModule2_HeapStorage_MsgInMapInHeapStorage.Sub: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = CrossModule2_HeapStorage_MsgInMapInHeapStorage.protoMessageName + ".Sub"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "a"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self._a)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._a {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public func _protobuf_generated_isEqualTo(other: CrossModule2_HeapStorage_MsgInMapInHeapStorage.Sub) -> Bool {
    if self._a != other._a {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
