/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: ChainB/file_b.proto
 *
 */

// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
// -----------------------------------------------------------------------------

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _1: SwiftProtobuf.ProtobufAPIVersion_1 {}
  typealias Version = _1
}

struct Chain_B_MessageB: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".MessageB"

  var fieldSint32: Int64 {
    get {return _storage._fieldSint32}
    set {_uniqueStorage()._fieldSint32 = newValue}
  }

  var fieldString: Data {
    get {return _storage._fieldString}
    set {_uniqueStorage()._fieldString = newValue}
  }

  var fieldMessage: Chain_A_MessageA {
    get {return _storage._fieldMessage ?? Chain_A_MessageA()}
    set {_uniqueStorage()._fieldMessage = newValue}
  }
  var hasFieldMessage: Bool {
    return _storage._fieldMessage != nil
  }
  mutating func clearFieldMessage() {
    _storage._fieldMessage = nil
  }

  var fieldEnum: Chain_A_EnumA {
    get {return _storage._fieldEnum}
    set {_uniqueStorage()._fieldEnum = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularInt64Field(value: &_storage._fieldSint32)
        case 2: try decoder.decodeSingularBytesField(value: &_storage._fieldString)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._fieldMessage)
        case 4: try decoder.decodeSingularEnumField(value: &_storage._fieldEnum)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._fieldSint32 != 0 {
        try visitor.visitSingularInt64Field(value: _storage._fieldSint32, fieldNumber: 1)
      }
      if !_storage._fieldString.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._fieldString, fieldNumber: 2)
      }
      if let v = _storage._fieldMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if _storage._fieldEnum != Chain_A_EnumA.foo {
        try visitor.visitSingularEnumField(value: _storage._fieldEnum, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass()
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "chain.b"

extension Chain_B_MessageB: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "field_sint32"),
    2: .standard(proto: "field_string"),
    3: .standard(proto: "field_message"),
    4: .standard(proto: "field_enum"),
  ]

  fileprivate class _StorageClass {
    var _fieldSint32: Int64 = 0
    var _fieldString: Data = SwiftProtobuf.Internal.emptyData
    var _fieldMessage: Chain_A_MessageA? = nil
    var _fieldEnum: Chain_A_EnumA = Chain_A_EnumA.foo

    init() {}

    init(copying source: _StorageClass) {
      _fieldSint32 = source._fieldSint32
      _fieldString = source._fieldString
      _fieldMessage = source._fieldMessage
      _fieldEnum = source._fieldEnum
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  func _protobuf_generated_isEqualTo(other: Chain_B_MessageB) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_storage, other_storage) in
        if _storage._fieldSint32 != other_storage._fieldSint32 {return false}
        if _storage._fieldString != other_storage._fieldString {return false}
        if _storage._fieldMessage != other_storage._fieldMessage {return false}
        if _storage._fieldEnum != other_storage._fieldEnum {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
