/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: ChainA/file_a.proto
 *
 */

// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
// -----------------------------------------------------------------------------

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _1: SwiftProtobuf.ProtobufAPIVersion_1 {}
  typealias Version = _1
}

public enum Chain_A_EnumA: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case foo // = 0
  case bar // = 1
  case baz // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .foo
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .foo
    case 1: self = .bar
    case 2: self = .baz
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .foo: return 0
    case .bar: return 1
    case .baz: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

public struct Chain_A_MessageA: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".MessageA"

  public var fieldInt64: Int64 {
    get {return _storage._fieldInt64}
    set {_uniqueStorage()._fieldInt64 = newValue}
  }

  public var fieldBytes: Data {
    get {return _storage._fieldBytes}
    set {_uniqueStorage()._fieldBytes = newValue}
  }

  public var fieldMessage: Chain_A_MessageA.SubMsg {
    get {return _storage._fieldMessage ?? Chain_A_MessageA.SubMsg()}
    set {_uniqueStorage()._fieldMessage = newValue}
  }
  public var hasFieldMessage: Bool {
    return _storage._fieldMessage != nil
  }
  public mutating func clearFieldMessage() {
    _storage._fieldMessage = nil
  }

  public var fieldEnum: Chain_A_EnumA {
    get {return _storage._fieldEnum}
    set {_uniqueStorage()._fieldEnum = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct SubMsg: SwiftProtobuf.Message {
    public static let protoMessageName: String = Chain_A_MessageA.protoMessageName + ".SubMsg"

    public var subFieldString: String = String()

    public var subFieldInt32: Int32 = 0

    public var subFieldBool: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &self.subFieldString)
        case 2: try decoder.decodeSingularInt32Field(value: &self.subFieldInt32)
        case 3: try decoder.decodeSingularBoolField(value: &self.subFieldBool)
        default: break
        }
      }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
      if !self.subFieldString.isEmpty {
        try visitor.visitSingularStringField(value: self.subFieldString, fieldNumber: 1)
      }
      if self.subFieldInt32 != 0 {
        try visitor.visitSingularInt32Field(value: self.subFieldInt32, fieldNumber: 2)
      }
      if self.subFieldBool != false {
        try visitor.visitSingularBoolField(value: self.subFieldBool, fieldNumber: 3)
      }
      try unknownFields.traverse(visitor: &visitor)
    }
  }

  public init() {}

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularInt64Field(value: &_storage._fieldInt64)
        case 2: try decoder.decodeSingularBytesField(value: &_storage._fieldBytes)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._fieldMessage)
        case 4: try decoder.decodeSingularEnumField(value: &_storage._fieldEnum)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._fieldInt64 != 0 {
        try visitor.visitSingularInt64Field(value: _storage._fieldInt64, fieldNumber: 1)
      }
      if !_storage._fieldBytes.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._fieldBytes, fieldNumber: 2)
      }
      if let v = _storage._fieldMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if _storage._fieldEnum != Chain_A_EnumA.foo {
        try visitor.visitSingularEnumField(value: _storage._fieldEnum, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass()
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "chain.a"

extension Chain_A_EnumA: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "FOO"),
    1: .same(proto: "BAR"),
    2: .same(proto: "BAZ"),
  ]
}

extension Chain_A_MessageA: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "field_int64"),
    2: .standard(proto: "field_bytes"),
    3: .standard(proto: "field_message"),
    4: .standard(proto: "field_enum"),
  ]

  fileprivate class _StorageClass {
    var _fieldInt64: Int64 = 0
    var _fieldBytes: Data = SwiftProtobuf.Internal.emptyData
    var _fieldMessage: Chain_A_MessageA.SubMsg? = nil
    var _fieldEnum: Chain_A_EnumA = Chain_A_EnumA.foo

    init() {}

    init(copying source: _StorageClass) {
      _fieldInt64 = source._fieldInt64
      _fieldBytes = source._fieldBytes
      _fieldMessage = source._fieldMessage
      _fieldEnum = source._fieldEnum
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: Chain_A_MessageA) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_storage, other_storage) in
        if _storage._fieldInt64 != other_storage._fieldInt64 {return false}
        if _storage._fieldBytes != other_storage._fieldBytes {return false}
        if _storage._fieldMessage != other_storage._fieldMessage {return false}
        if _storage._fieldEnum != other_storage._fieldEnum {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Chain_A_MessageA.SubMsg: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "sub_field_string"),
    2: .standard(proto: "sub_field_int32"),
    3: .standard(proto: "sub_field_bool"),
  ]

  public func _protobuf_generated_isEqualTo(other: Chain_A_MessageA.SubMsg) -> Bool {
    if self.subFieldString != other.subFieldString {return false}
    if self.subFieldInt32 != other.subFieldInt32 {return false}
    if self.subFieldBool != other.subFieldBool {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
