// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: test_hooks_same_module3_heap_storage.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct SameModule3_HeapStorage_Msg {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var field1: Int32 {
    get {return _storage._field1}
    set {_uniqueStorage()._field1 = newValue}
  }

  var field2: Int32 {
    get {return _storage._field2}
    set {_uniqueStorage()._field2 = newValue}
  }

  var forceHeapStorage: SameModule3_HeapStorage_Msg.Sub {
    get {return _storage._forceHeapStorage ?? SameModule3_HeapStorage_Msg.Sub()}
    set {_uniqueStorage()._forceHeapStorage = newValue}
  }
  /// Returns true if `forceHeapStorage` has been explicitly set.
  var hasForceHeapStorage: Bool {return _storage._forceHeapStorage != nil}
  /// Clears the value of `forceHeapStorage`. Subsequent reads from it will return its default value.
  mutating func clearForceHeapStorage() {_storage._forceHeapStorage = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Forcing this message to use heap storage.
  struct Sub {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var a: Int32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct SameModule3_HeapStorage_MsgAsField {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var asField: SameModule3_HeapStorage_Msg {
    get {return _storage._asField ?? SameModule3_HeapStorage_Msg()}
    set {_uniqueStorage()._asField = newValue}
  }
  /// Returns true if `asField` has been explicitly set.
  var hasAsField: Bool {return _storage._asField != nil}
  /// Clears the value of `asField`. Subsequent reads from it will return its default value.
  mutating func clearAsField() {_storage._asField = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct SameModule3_HeapStorage_MsgInArray {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var inArray: [SameModule3_HeapStorage_Msg] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct SameModule3_HeapStorage_MsgInArrayInHeapStorage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var inArray: [SameModule3_HeapStorage_Msg] {
    get {return _storage._inArray}
    set {_uniqueStorage()._inArray = newValue}
  }

  var forceHeapStorage: SameModule3_HeapStorage_MsgInArrayInHeapStorage.Sub {
    get {return _storage._forceHeapStorage ?? SameModule3_HeapStorage_MsgInArrayInHeapStorage.Sub()}
    set {_uniqueStorage()._forceHeapStorage = newValue}
  }
  /// Returns true if `forceHeapStorage` has been explicitly set.
  var hasForceHeapStorage: Bool {return _storage._forceHeapStorage != nil}
  /// Clears the value of `forceHeapStorage`. Subsequent reads from it will return its default value.
  mutating func clearForceHeapStorage() {_storage._forceHeapStorage = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Forcing this message to use heap storage.
  struct Sub {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var a: Int32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct SameModule3_HeapStorage_MsgInMap {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var inMap: Dictionary<Int32,SameModule3_HeapStorage_Msg> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct SameModule3_HeapStorage_MsgInMapInHeapStorage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var inMap: Dictionary<Int32,SameModule3_HeapStorage_Msg> {
    get {return _storage._inMap}
    set {_uniqueStorage()._inMap = newValue}
  }

  var forceHeapStorage: SameModule3_HeapStorage_MsgInMapInHeapStorage.Sub {
    get {return _storage._forceHeapStorage ?? SameModule3_HeapStorage_MsgInMapInHeapStorage.Sub()}
    set {_uniqueStorage()._forceHeapStorage = newValue}
  }
  /// Returns true if `forceHeapStorage` has been explicitly set.
  var hasForceHeapStorage: Bool {return _storage._forceHeapStorage != nil}
  /// Clears the value of `forceHeapStorage`. Subsequent reads from it will return its default value.
  mutating func clearForceHeapStorage() {_storage._forceHeapStorage = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Forcing this message to use heap storage.
  struct Sub {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var a: Int32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "same_module3.heap_storage"

extension SameModule3_HeapStorage_Msg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Msg"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "field1"),
    2: .same(proto: "field2"),
    3: .standard(proto: "force_heap_storage"),
  ]

  fileprivate class _StorageClass {
    var _field1: Int32 = 0
    var _field2: Int32 = 0
    var _forceHeapStorage: SameModule3_HeapStorage_Msg.Sub? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _field1 = source._field1
      _field2 = source._field2
      _forceHeapStorage = source._forceHeapStorage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularInt32Field(value: &_storage._field1)
        case 2: try decoder.decodeSingularInt32Field(value: &_storage._field2)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._forceHeapStorage)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._field1 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._field1, fieldNumber: 1)
      }
      if _storage._field2 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._field2, fieldNumber: 2)
      }
      if let v = _storage._forceHeapStorage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: SameModule3_HeapStorage_Msg) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._field1 != other_storage._field1 {return false}
        if _storage._field2 != other_storage._field2 {return false}
        if _storage._forceHeapStorage != other_storage._forceHeapStorage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension SameModule3_HeapStorage_Msg.Sub: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = SameModule3_HeapStorage_Msg.protoMessageName + ".Sub"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "a"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.a)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.a != 0 {
      try visitor.visitSingularInt32Field(value: self.a, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: SameModule3_HeapStorage_Msg.Sub) -> Bool {
    if self.a != other.a {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension SameModule3_HeapStorage_MsgAsField: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MsgAsField"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "as_field"),
  ]

  fileprivate class _StorageClass {
    var _asField: SameModule3_HeapStorage_Msg? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _asField = source._asField
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._asField)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._asField {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: SameModule3_HeapStorage_MsgAsField) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._asField != other_storage._asField {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension SameModule3_HeapStorage_MsgInArray: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MsgInArray"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "inArray"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.inArray)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.inArray.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.inArray, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: SameModule3_HeapStorage_MsgInArray) -> Bool {
    if self.inArray != other.inArray {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension SameModule3_HeapStorage_MsgInArrayInHeapStorage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MsgInArrayInHeapStorage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "inArray"),
    2: .standard(proto: "force_heap_storage"),
  ]

  fileprivate class _StorageClass {
    var _inArray: [SameModule3_HeapStorage_Msg] = []
    var _forceHeapStorage: SameModule3_HeapStorage_MsgInArrayInHeapStorage.Sub? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _inArray = source._inArray
      _forceHeapStorage = source._forceHeapStorage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeRepeatedMessageField(value: &_storage._inArray)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._forceHeapStorage)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._inArray.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._inArray, fieldNumber: 1)
      }
      if let v = _storage._forceHeapStorage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: SameModule3_HeapStorage_MsgInArrayInHeapStorage) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._inArray != other_storage._inArray {return false}
        if _storage._forceHeapStorage != other_storage._forceHeapStorage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension SameModule3_HeapStorage_MsgInArrayInHeapStorage.Sub: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = SameModule3_HeapStorage_MsgInArrayInHeapStorage.protoMessageName + ".Sub"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "a"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.a)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.a != 0 {
      try visitor.visitSingularInt32Field(value: self.a, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: SameModule3_HeapStorage_MsgInArrayInHeapStorage.Sub) -> Bool {
    if self.a != other.a {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension SameModule3_HeapStorage_MsgInMap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MsgInMap"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "in_map"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt32,SameModule3_HeapStorage_Msg>.self, value: &self.inMap)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.inMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt32,SameModule3_HeapStorage_Msg>.self, value: self.inMap, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: SameModule3_HeapStorage_MsgInMap) -> Bool {
    if self.inMap != other.inMap {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension SameModule3_HeapStorage_MsgInMapInHeapStorage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MsgInMapInHeapStorage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "in_map"),
    2: .standard(proto: "force_heap_storage"),
  ]

  fileprivate class _StorageClass {
    var _inMap: Dictionary<Int32,SameModule3_HeapStorage_Msg> = [:]
    var _forceHeapStorage: SameModule3_HeapStorage_MsgInMapInHeapStorage.Sub? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _inMap = source._inMap
      _forceHeapStorage = source._forceHeapStorage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt32,SameModule3_HeapStorage_Msg>.self, value: &_storage._inMap)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._forceHeapStorage)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._inMap.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt32,SameModule3_HeapStorage_Msg>.self, value: _storage._inMap, fieldNumber: 1)
      }
      if let v = _storage._forceHeapStorage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: SameModule3_HeapStorage_MsgInMapInHeapStorage) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._inMap != other_storage._inMap {return false}
        if _storage._forceHeapStorage != other_storage._forceHeapStorage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension SameModule3_HeapStorage_MsgInMapInHeapStorage.Sub: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = SameModule3_HeapStorage_MsgInMapInHeapStorage.protoMessageName + ".Sub"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "a"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.a)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.a != 0 {
      try visitor.visitSingularInt32Field(value: self.a, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  func _protobuf_generated_isEqualTo(other: SameModule3_HeapStorage_MsgInMapInHeapStorage.Sub) -> Bool {
    if self.a != other.a {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
